apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: garage-namespace
spec:
  ports:
    - port: 5672
      targetPort: 5672
      name: rabbitmq-port
    - port: 15672
      targetPort: 15672
      name: rabbitmq-management
  selector:
    app: rabbitmq
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-statefulset
  namespace: garage-namespace
spec:
  serviceName: rabbitmq-service
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-container
          image: rabbitmq:4.0-management
          ports:
            - containerPort: 5672   # RabbitMQ AMQP port
            - containerPort: 15672  # RabbitMQ management UI
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq

  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi