apiVersion: v1
kind: Service
metadata:
  name: mongo-invoice-service
  namespace: garage-namespace
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-invoice-statefulset
  namespace: garage-namespace
spec:
  serviceName: mongo-invoice-service
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo-invoice-container
          image: mongo:latest
          ports:
            - containerPort: 27017
              name: mongo-port
          volumeMounts:
            - name: mongovol
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password

  volumeClaimTemplates:
    - metadata:
        name: mongovol
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
