apiVersion: v1
kind: Service
metadata:
  name: mysql-workshop-service
  namespace: garage-namespace
spec:
  selector:
    app: mysql-workshop
  ports:
    - port: 5435
      protocol: TCP
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-workshop-statefulset
  namespace: garage-namespace
spec:
  replicas: 1
  serviceName: mysql-workshop-service
  selector:
    matchLabels:
      app: mysql-workshop
  template:
    metadata:
      labels:
        app: mysql-workshop
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql-workshop-container
          image: mysql:9 
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          ports:
            - containerPort: 3306  
              name: mysql-db-port
          volumeMounts:
            - name: mysqlvol
              mountPath: /var/lib/mysql  
  volumeClaimTemplates:
    - metadata:
        name: mysqlvol
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
