apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-service
  namespace: garage-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop-service
  template:
    metadata:
      labels:
        app: workshop-service
    spec:
      containers:
        - name: workshop-service
          image: bouihassan/garage-management-workshop-service:1.1.2
          ports:
            - containerPort: 8083

          env:
            - name: PROFILE
              value: prod

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: workshop-conf
                  key: DB_HOST
                  
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: workshop-conf
                  key: DB_NAME

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: workshop-conf
                  key: DB_PORT

            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: workshop-conf
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: workshop-service
  namespace: garage-namespace
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: workshop-service
  type: NodePort
