apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-frontend
  namespace: garage-namespace
  labels:
    app: garage-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: garage-frontend
  template:
    metadata:
      labels:
        app: garage-frontend
    spec:
      containers:
        - name: garage-frontend
          image: bouihassan/garage-management-frontend:1.1.3
          ports:
            - containerPort: 3000
          env:                                  
            - name: REACT_APP_API_GATEWAY
              value: "http://localhost:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: garage-frontend-service
  namespace: garage-namespace
  labels:
    app: garage-frontend
spec:
  type: LoadBalancer
  selector:
    app: garage-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
