apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: garage-namespace
  labels:
    app: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: garage-namespace
  labels:
    app: api-gateway
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: garage-gateway
          image: bouihassan/garage-management-gateway:1.1.3
          ports:
            - containerPort: 8080
          envFrom:         
            - configMapRef:
                name: api-gateway-config

