apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: garage-namespace
data:
  password: bXlzcWw=      #base64 encoded
  username: cm9vdA==
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: garage-namespace
data:
  password: bW9uZ28=
  username: bW9uZ28=
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: garage-namespace
data:
  password: cG9zdGdyZXM=
  username: cG9zdGdyZXM=