apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: garage-namespace
  labels:
    app: api-gateway
data:
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1,http://garage-frontend:3000"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "*"
  CORS_ALLOW_CREDENTIALS: "true"
  CLIENT_SERVICE_URL: "http://client-service:8081"
  VEHICULE_SERVICE_URL: "http://vehicule-service:8082"
  WORKSHOP_SERVICE_URL: "http://workshop-service:8083"
  INVOICE_SERVICE_URL: "http://invoice-service:8084"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8085"
