apiVersion: v1
kind: ConfigMap
metadata:
  name: vehicule-conf
  namespace: garage-namespace
data:
  DB_NAME: "vehicule_db"
  DB_PORT: "5434"
  DB_HOST: "postgres-vehicule-service"
  DB_USERNAME: "postgres"
